### ISSUE TITLE
Winapi: Image should use CF_BITMAP?

### ISSUE THREAD

**Issue by DoumanAsh** [ArturKovacs/arboard#1]
JFYI you can get image by using high level format type https://docs.rs/clipboard-win/4.0.2/clipboard_win/formats/struct.Bitmap.html
It is to be used within context of opened clipboard.

See Getter/Setter traits.
If you want you can add CF_DIB to code by making PR
There are also shortcut functions that open/close clipboard and get data to owned data structure if you don't need to efficiently re-use buffers https://docs.rs/clipboard-win/4.0.2/clipboard_win/fn.get_clipboard.html

**Comment by ArturKovacs** [comment]
I tried using the Bitmap format but it seems to me that it doesn't support alpha so I figured it's easier if I just re-implement that myself.

The reason for me separating the clipboard opening and the data transfer is to be able to tell if the error was because the clipboard is being used or if it's because the data cannot be transferred.

**Comment by DoumanAsh** [comment]
Yes, that's correct CF_BITMAP doesn't allow you to store alpha channel.
But afaik most, programs, if not all, are not able to work with it properly also.

**Comment by ArturKovacs** [comment]
[Emulsion](https://github.com/ArturKovacs/emulsion) is 😁

**Comment by DoumanAsh** [comment]
Ah, I see.
As side note I suggest to take a look at how Firefox and other applications register `PNG` format and copy/paste in PNG format.
It might be even better option for image viewer

**Comment by ArturKovacs** [comment]
Thanks, should be useful for large image files. I opened #2
