### ISSUE TITLE
Comparing ImageData

### ISSUE THREAD

**Issue by MordechaiHadad** [ArturKovacs/arboard#31]
Is there any way to compare ImageData?

**Comment by ArturKovacs** [comment]
`ImageData` doesn't implement any comparison operators such as `std::cmp::PartialEq`, but all of its fields are public so you can compare those one-by-one. (Because `Cow` [implements](https://doc.rust-lang.org/std/borrow/enum.Cow.html#impl-PartialEq%3CCow%3C%27b%2C%20C%3E%3E) `PartialEq` when its contained type also does)

I do not recommend doing this. I would say that in most cases you don't want to do this, because comparing all bytes in large images is slow.

But if you really just want see if the two images are identical in all ways, then you can check that like this for example:
```rs
fn same_image<'a, 'b>(a: &ImageData<'a>, b: &ImageData<'b>) -> bool {
	return a.width == b.width && a.height == b.height && a.bytes == b.bytes;
}
```

I'm closing this as I assume it answered the question. Let me know if it didn't.

**Comment by MordechaiHadad** [comment]
> `ImageData` doesn't implement any comparison operators such as `std::cmp::PartialEq`, but all of its fields are public so you can compare those one-by-one. (Because `Cow` [implements](https://doc.rust-lang.org/std/borrow/enum.Cow.html#impl-PartialEq%3CCow%3C%27b%2C%20C%3E%3E) `PartialEq` when its contained type also does)
> 
> I do not recommend doing this. I would say that in most cases you don't want to do this, because comparing all bytes in large images is slow.
> 
> But if you really just want see if the two images are identical in all ways, then you can check that like this for example:
> 
> ```rust
> fn same_image<'a, 'b>(a: &ImageData<'a>, b: &ImageData<'b>) -> bool {
> 	return a.width == b.width && a.height == b.height && a.bytes == b.bytes;
> }
> ```
> 
> I'm closing this as I assume it answered the question. Let me know if it didn't.

You absolutely did thank you, 🤣 i tried for looping through each byte at first but couldn't cuz cant cast [u8] to iterator. 
anyway thanks.
